### ISSUE TITLE
The latest release requires a higher version of gotrue than advertised

### ISSUE THREAD

**Issue by jfeaver** [supabase/supabase-py#943] opened 2024-09-29 22:15 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I've got my `gotrue` Python package pinned at 2.5.1 (because our Supabase stack is out of date and otherwise I get an error about not receiving an `identity_id`). When I update to the latest `supabase` package version and then start my application, I get an error about a missing import:

```
  File "/Users/nathan/Library/Caches/pypoetry/virtualenvs/my-project-odHRiFV8-py3.12/lib/python3.12/site-packages/supabase/__init__.py", line 1, in <module>
    from gotrue.errors import (
ImportError: cannot import name 'AuthWeakPasswordError' from 'gotrue.errors' (/Users/nathan/Library/Caches/pypoetry/virtualenvs/my-project-odHRiFV8-py3.12/lib/python3.12/site-packages/gotrue/errors.py)
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Build an application that has these dependencies in pyproject.toml

```
[tool.poetry.dependencies]
gotrue = "<=2.5.1"
supabase = "^2"
```
2. Start the application (you may need to import something from supabase)
3. See an error

## Expected behavior

The application should start without an error

## System information

- OS: macOS 14.3.1 (23D60)
- supabase-py v2.8.0

**Comment by silentworks** [comment] 2024-09-29 22:43
You should pin your `supabase-py` version if this is your desired outcome.

**Comment by silentworks** [comment] 2024-10-18 12:27
Closing this out as it's not a bug.

**Closed by silentworks** 2024-10-18 12:27 UTC
Labels: bug
