### ISSUE TITLE
If supabase url contains a trailing slash, `insert` statements return 404s with a cryptic error message

### ISSUE THREAD

**Issue by lukaszdz** [supabase/supabase-py#959] opened 2024-10-08 06:01 UTC
# Bug report

## Describe the bug

In supabase.py, when `SUPABASE_URL` is set with a trailing slash, insert statements trigger a 404 error. When the slash is removed, insert statements are successful.

## To Reproduce

```
import os

from supabase import Client, create_client

# NOTE: os.environ.get("SUPABASE_URL") ends with a trailing slash

_supabase: Client = create_client(
    os.environ.get("SUPABASE_URL")[:-1], os.environ.get("SUPABASE_SERVICE_KEY")
)
_supabase.table("charles").insert(json={"says": "sup"}).execute() # SUCCESSFUL

_supabase: Client = create_client(
    os.environ.get("SUPABASE_URL"), os.environ.get("SUPABASE_SERVICE_KEY")
)
_supabase.table("charles").insert(json={"says": "sup2"}).execute()  # ERRORS

```

## Expected behavior

I expected the insert statement to work for URLs containing a trailing slash as well as without a trailing slash. Alternatively, would be nice if there was a way to validate the URL and KEY so they fail right away instead of giving cryptic 404s.

## Screenshots

In the following image, the url without the slash runs in the top insert, and leaves the slash in for the second statement. Note that the highlighted line is where the error is thrown.

<img width="806" alt="image" src="https://github.com/user-attachments/assets/f8811161-5523-46fa-a129-e2ebafa4602b">

The reuslting error message is cryptic as well:
<img width="1170" alt="image" src="https://github.com/user-attachments/assets/a4a1bb56-1ebc-44c2-8ab6-96da26462e74">

## System information

- OS: [ubuntu]
- Version of supabase-py
```
supabase==2.7.4
supabase-py-async==2.5.6
```

**Comment by silentworks** [comment] 2024-10-09 17:58
Not a bug, the dashboard doesn't provide a URL with a trailing slash, this is an user error.

**Comment by lukaszdz** [comment] 2024-10-09 18:37
Hey - your team fixed this in js (https://github.com/supabase/supabase-js/issues/261), why not here? fix is easy. Cryptic error message made it difficult to determine the root case of this issue.

**Comment by silentworks** [comment] 2024-10-10 22:47
I've tested this in the latest `supabase` python library and cannot replicate this issue.

**Comment by silentworks** [comment] 2024-11-12 22:51
No update from the OP. I've added a video demonstrating this working. I'm closing this out for now.

https://github.com/user-attachments/assets/012319d0-4e91-4371-b9e6-160f72226461

**Closed by silentworks** 2024-11-12 22:51 UTC
Labels: bug
